server.port: 8085

spring:
  jpa:
    hibernate.ddl-auto=update: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/online-shop?serverTimezone=UTC
    username: online-shop-Admin1
    password: online-shop-Admin1




